using ILGPU;
using ILGPU.Algorithms;
using ILGPU.Backends.EntryPoints;
using ILGPU.Backends.PTX;
using ILGPU.Runtime;
using ILGPU.Runtime.Cuda;
using Sezika.Kernels;
using System.Reflection;
using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Security.Cryptography;

using var context = Context.Create(builder => builder.EnableAlgorithms().Math(MathMode.Default));
using var backend = new PTXBackend(context, new CudaArchitecture(7, 0), new CudaInstructionSet(7, 0), null!);

var outputDirectory = args.Length == 0 ? Path.Combine("artifacts", "kernels") : Path.GetFullPath(args[0]);
Directory.CreateDirectory(outputDirectory);
var names = new[]
{
    nameof(TransformerKernels.VectorAdd), nameof(TransformerKernels.Linear), nameof(TransformerKernels.Embedding),
    nameof(TransformerKernels.Norm), nameof(TransformerKernels.SplitQkv), nameof(TransformerKernels.Rope),
    nameof(TransformerKernels.AttentionScores), nameof(TransformerKernels.Softmax), nameof(TransformerKernels.AttentionContext),
    nameof(TransformerKernels.Add), nameof(TransformerKernels.Activate), nameof(TransformerKernels.GatedGelu),
    nameof(TransformerKernels.RowBias), nameof(TransformerKernels.TypeEmbeddingAdd),
};
var records = new List<KernelRecord>(names.Length);
var source = new StringBuilder("// Generated by Sezika.KernelCompiler; do not edit.\nnamespace Sezika.Cuda;\n\ninternal static class GeneratedKernelArtifacts\n{\n    internal readonly record struct Descriptor(string Entry, int ParameterCount, int BlockSize);\n");
var sourcePath = Path.Combine("src", "Sezika.Kernels", "TransformerKernels.cs");
var sourceHash = File.Exists(sourcePath) ? Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(sourcePath))) : throw new FileNotFoundException("C# kernel source is missing.", sourcePath);
source.Append("    internal const string CompilerVersion = \"ILGPU 1.5.3\";\n    internal const string SourceSha256 = \"").Append(sourceHash).Append("\";\n");
foreach (var name in names)
{
    var method = typeof(TransformerKernels).GetMethod(name, BindingFlags.Public | BindingFlags.Static)!;
    var description = EntryPointDescription.FromExplicitlyGroupedKernel(method);
    var kernel = (PTXCompiledKernel)backend.Compile(description, KernelSpecialization.Empty);
    var ptx = kernel.PTXAssembly.Replace("\r\n", "\n", StringComparison.Ordinal).Replace('\r', '\n').TrimEnd() + "\0";
    var entry = Regex.Match(ptx, @"\.visible \.entry\s+(?<name>[A-Za-z0-9_]+)\s*\(").Groups["name"].Value;
    if (string.IsNullOrWhiteSpace(entry)) throw new InvalidOperationException($"No PTX entry found for {name}.");
    var abi = ParseAbi(ptx, method);
    var file = name + ".ptx";
    var ptxBytes = Encoding.ASCII.GetBytes(ptx);
    File.WriteAllBytes(Path.Combine(outputDirectory, file), ptxBytes);
    source.Append("    internal static ReadOnlySpan<byte> ").Append(name).Append(" => new byte[] { ");
    foreach (var value in Encoding.ASCII.GetBytes(ptx)) source.Append("0x").Append(value.ToString("X2")).Append(", ");
    source.Append("};\n");
    source.Append("    internal static Descriptor ").Append(name).Append("Descriptor => new(\"").Append(entry).Append("\", ").Append(abi.Length).Append(", 256);\n");
    records.Add(new KernelRecord(name, entry, file, Convert.ToHexString(SHA256.HashData(ptxBytes)), 256, abi));
}
source.Append("}\n");
// Use a BOM-free encoding so generated artifacts are byte-for-byte reproducible
// across the Windows and Linux build tools. The manifest and checked-in source
// are hashed as bytes, so an implicit UTF-8 BOM would invalidate the manifest.
var utf8NoBom = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false);
File.WriteAllText(Path.Combine(outputDirectory, "GeneratedKernelArtifacts.g.cs"), source.ToString(), utf8NoBom);
var manifest = new { schemaVersion = 1, compiler = "ILGPU", compilerVersion = "1.5.3", target = "sm_70", ptxVersion = "7.0", sourceSha256 = sourceHash, kernels = records };
var manifestJson = JsonSerializer.Serialize(manifest, new JsonSerializerOptions { WriteIndented = true, PropertyNamingPolicy = JsonNamingPolicy.CamelCase })
    .Replace("\r\n", "\n", StringComparison.Ordinal);
File.WriteAllText(Path.Combine(outputDirectory, "kernel-manifest.json"), manifestJson, utf8NoBom);
Console.WriteLine($"Generated {records.Count} PTX kernels at {outputDirectory}.");

static KernelParameter[] ParseAbi(string ptx, MethodInfo method)
{
    var lines = ptx.Split('\n');
    var values = new List<(string Type, int Width, int Alignment)>();
    foreach (var line in lines)
    {
        var match = Regex.Match(line.Trim(), @"^\.param(?: \.align (?<align>\d+))? \.(?:b|f)(?<bits>8|32|64)(?: (?<name>[A-Za-z0-9_]+)\[(?<array>\d+)\])?");
        if (!match.Success) continue;
        var bits = int.Parse(match.Groups["bits"].Value, CultureInfo.InvariantCulture);
        var width = match.Groups["array"].Success ? int.Parse(match.Groups["array"].Value, CultureInfo.InvariantCulture) : bits / 8;
        var alignment = match.Groups["align"].Success ? int.Parse(match.Groups["align"].Value, CultureInfo.InvariantCulture) : Math.Min(width, 4);
        values.Add((match.Groups["array"].Success ? "device_view" : bits == 32 ? "scalar32" : "scalar64", width, alignment));
    }
    var parameters = method.GetParameters();
    if (values.Count != parameters.Length) throw new InvalidOperationException($"ABI count mismatch for {method.Name}: PTX={values.Count}, C#={parameters.Length}.\n{ptx}");
    var result = new KernelParameter[parameters.Length];
    for (var i = 0; i < parameters.Length; i++)
    {
        var expected = parameters[i].ParameterType.IsGenericType && parameters[i].ParameterType.GetGenericTypeDefinition() == typeof(ArrayView<>) ? ("device_view", 16, 8) : parameters[i].ParameterType == typeof(float) ? ("scalar32", 4, 4) : ("scalar32", 4, 4);
        if (values[i] != expected) throw new InvalidOperationException($"ABI mismatch for {method.Name} parameter {parameters[i].Name}: got {values[i]}, expected {expected}.");
        result[i] = new KernelParameter(parameters[i].Name!, expected.Item1, expected.Item2, expected.Item3);
    }
    return result;
}

public sealed record KernelParameter(string Name, string Kind, int Width, int Alignment);
public sealed record KernelRecord(string Name, string Entry, string Ptx, string Sha256, int BlockSize, KernelParameter[] Parameters);
