<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Sezika.Cli</AssemblyName>
    <RootNamespace>Sezika.Cli</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishAot>true</PublishAot>
    <StripSymbols>true</StripSymbols>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <EnableAotAnalyzer>true</EnableAotAnalyzer>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Sezika/Sezika.csproj" />
  </ItemGroup>
</Project>
